stages:
  - build
  - deploy
build:
  image: node:16.13  # Run the job in a `node` docker image
  stage: build
  script:
    - CI=false npm install      # Run `yarn install` and `yarn build`
    - CI=false npm run build
  artifacts:
    paths:
      - build/  
pages:
  image: alpine:latest
  stage: deploy
  script:
    - mv build public         
  artifacts:
    paths:
      - public
