name: playElu page

on:
  repository_dispatch:
  push:
    branches:
      - dung97

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: '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'
        publish_dir: ./build